### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by morontt** [vavilen84/tiz#1]
Не хватает ссылки на фид, если он уже есть. Непонятно как подписаться.

Также отсутствуют метатеги для фида в HTML-е, вроде тех, что ниже, так что и агрегаторы фидов тоже ничего не видят на сайте.

    <link href="https://morontt.info/feed/rss" rel="alternate" type="application/rss+xml" title="RSS" >
    <link href="https://morontt.info/feed/atom" rel="alternate" type="application/atom+xml" title="Atom" >

**Comment by vavilen84** [comment]
щас добавим

**Comment by vavilen84** [comment]
ссылка будет в футере, тока там надо 6 постов чтобы он появился))

**Comment by morontt** [comment]
Что за странное безумие - футер только когда 6 постов? :)

**Comment by vavilen84** [comment]
ну там так получилось)) футер есть пагинация. и вот ссылку туда же засунул)))
